// packages/memos-embed-react/src/index.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import type {
	EmbedHtmlOptions,
	EmbedRenderOptions,
	Memo,
	ThemeInput,
} from "memos-embed";
import {
	fetchMemo,
	renderMemoHtmlSnippet,
	renderMemoStateHtmlSnippet,
} from "memos-embed";

export type MemoEmbedProps = {
	memoId: string;
	baseUrl: string;
	theme?: ThemeInput;
	density?: EmbedRenderOptions["density"];
	locale?: string;
	showTags?: boolean;
	showAttachments?: boolean;
	showReactions?: boolean;
	showMeta?: boolean;
	onError?: (error: Error) => void;
	onLoad?: (memo: Memo) => void;
};

export const MemoEmbed = ({
	memoId,
	baseUrl,
	theme,
	density,
	locale,
	showTags,
	showAttachments,
	showReactions,
	showMeta,
	onError,
	onLoad,
}: MemoEmbedProps) => {
	const [memo, setMemo] = useState<Memo | null>(null);
	const [error, setError] = useState<Error | null>(null);
	const containerRef = useRef<HTMLDivElement | null>(null);

	const renderOptions: EmbedRenderOptions = useMemo(
		() => ({
			theme,
			density,
			locale,
			showTags,
			showAttachments,
			showReactions,
			showMeta,
		}),
		[
			theme,
			density,
			locale,
			showTags,
			showAttachments,
			showReactions,
			showMeta,
		],
	);

	const htmlOptions: EmbedHtmlOptions = useMemo(
		() => ({
			...renderOptions,
			includeStyles: true,
		}),
		[renderOptions],
	);

	useEffect(() => {
		const controller = new AbortController();
		let isMounted = true;
		setError(null);
		setMemo(null);

		fetchMemo({ baseUrl, memoId, signal: controller.signal })
			.then((data: Memo) => {
				if (!isMounted || controller.signal.aborted) {
					return;
				}
				setMemo(data);
				onLoad?.(data);
			})
			.catch((fetchError: Error) => {
				if (!isMounted || controller.signal.aborted) {
					return;
				}
				setError(fetchError);
				onError?.(fetchError);
			});

		return () => {
			isMounted = false;
			controller.abort();
		};
	}, [baseUrl, memoId, onError, onLoad]);

	useEffect(() => {
		if (!memo || !containerRef.current) {
			return;
		}
		containerRef.current.innerHTML = renderMemoHtmlSnippet(memo, htmlOptions);
	}, [memo, htmlOptions]);

	if (error) {
		return (
			<div
				dangerouslySetInnerHTML={{
					__html: renderMemoStateHtmlSnippet("Failed to load memo."),
				}}
			/>
		);
	}

	if (!memo) {
		return (
			<div
				dangerouslySetInnerHTML={{
					__html: renderMemoStateHtmlSnippet("Loading memo…"),
				}}
			/>
		);
	}

	return <div className="memos-embed__container" ref={containerRef} />;
};

// packages/memos-embed-wc/src/index.ts
import {
	fetchMemo,
	renderMemoHtmlSnippet,
	renderMemoStateHtmlSnippet,
	type EmbedRenderOptions,
	type ThemeInput,
} from "memos-embed";

const attributeToBoolean = (value: string | null) => {
	if (value === null) {
		return undefined;
	}
	return value === "" || value === "true";
};

const HTMLElementBase =
	(globalThis as { HTMLElement?: typeof HTMLElement }).HTMLElement ??
	(class {} as typeof HTMLElement);

export class MemosEmbedElement extends HTMLElementBase {
	static get observedAttributes() {
		return [
			"memo-id",
			"base-url",
			"theme",
			"density",
			"locale",
			"show-tags",
			"show-attachments",
			"show-reactions",
			"show-meta",
		];
	}

	private readonly shadowRootRef: ShadowRoot;
	private abortController?: AbortController;
	private renderToken = 0;

	constructor() {
		super();
		this.shadowRootRef = this.attachShadow({ mode: "open" });
	}

	connectedCallback() {
		void this.render();
	}

	disconnectedCallback() {
		this.abortController?.abort();
	}

	attributeChangedCallback() {
		void this.render();
	}

	private getRenderOptions(): EmbedRenderOptions {
		return {
			theme:
				(this.getAttribute("theme") as ThemeInput | undefined) ?? undefined,
			density:
				(this.getAttribute("density") as EmbedRenderOptions["density"]) ??
				undefined,
			locale: this.getAttribute("locale") ?? undefined,
			showTags: attributeToBoolean(this.getAttribute("show-tags")),
			showAttachments: attributeToBoolean(
				this.getAttribute("show-attachments"),
			),
			showReactions: attributeToBoolean(this.getAttribute("show-reactions")),
			showMeta: attributeToBoolean(this.getAttribute("show-meta")),
		};
	}

	private async render() {
		const memoId = this.getAttribute("memo-id");
		const baseUrl = this.getAttribute("base-url");

		if (!memoId || !baseUrl) {
			this.shadowRootRef.innerHTML = renderMemoStateHtmlSnippet(
				"Missing memo-id or base-url.",
			);
			return;
		}

		this.abortController?.abort();
		const controller = new AbortController();
		this.abortController = controller;
		const currentToken = ++this.renderToken;

		this.shadowRootRef.innerHTML = renderMemoStateHtmlSnippet("Loading memo…");

		try {
			const memo = await fetchMemo({
				baseUrl,
				memoId,
				signal: controller.signal,
			});
			if (controller.signal.aborted || currentToken !== this.renderToken) {
				return;
			}
			this.shadowRootRef.innerHTML = renderMemoHtmlSnippet(
				memo,
				this.getRenderOptions(),
			);
		} catch (error) {
			if (controller.signal.aborted || currentToken !== this.renderToken) {
				return;
			}
			const message =
				error instanceof Error ? error.message : "Failed to load memo.";
			this.shadowRootRef.innerHTML = renderMemoStateHtmlSnippet(message);
		}
	}
}

export const defineMemosEmbedElement = () => {
	if (!customElements.get("memos-embed")) {
		customElements.define("memos-embed", MemosEmbedElement);
	}
};
